/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.hello;

import org.hello.client.HelloClient;
import org.hello.exception.HelloException;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.display.Password;
import org.mule.api.annotations.lifecycle.Start;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name = "hello", schemaVersion = "1.0-SNAPSHOT", friendlyName = "Hello", minMuleVersion = "3.4")
public class HelloConnector {
    static final private Log logger = LogFactory.getLog(HelloConnector.class);

    /**
     * CloudHub API Url
     */
    @Configurable
    @Optional
    @Default("http://reyness.cloudhub.io")
    private String apiUrl;


    /**
     * Port
     */
    @Configurable
    private String port;


    /**
     * HelloClient
     */
    HelloClient helloClient;

    @Start
    public void init() {
        setHelloClient(new HelloClient(this));
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        if (helloClient != null) {
            helloClient = null;
        }
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return true;
    }

    /**
     * Connection identifier
     */
    @ConnectionIdentifier
    public String connectionId() {
        return "001";
    }

    /**
     * Get the Hello Message processed by the web Service
     * <p/>
     * {@sample.xml ../../../doc/Hello-connector.xml.sample hello:get-hello}
     *
     * @param company Company Name
     * @param fname   First Name
     * @param lname   Last Name
     * @return Name of formatted String
     * @throws org.hello.exception.HelloException Exception when encountered an error
     */
    @Processor
    public String getHello(String company, String fname, String lname) throws HelloException {
        return getHelloClient().getHello(company, fname, lname);
    }

    public String getApiUrl() {
        return apiUrl;
    }

    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl;
    }

    public HelloClient getHelloClient() {
        return helloClient;
    }

    public void setHelloClient(HelloClient helloClient) {
        this.helloClient = helloClient;
    }

    public String getPort() {
        return port;
    }

    public void setPort(String port) {
        this.port = port;
    }

}
