/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.hello.client;
/**
 * Created by alexfernandezwhiteskylabs on 5/8/14.
 */

import com.sun.jersey.api.client.*;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.api.json.JSONConfiguration;
import com.sun.jersey.core.util.MultivaluedMapImpl;
import org.hello.HelloConnector;
import org.hello.exception.HelloException;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;

public class HelloClient {
    private Client client;
    private WebResource apiResource;
    private HelloConnector connector;

    public HelloClient(HelloConnector connector) {
        setConnector(connector);
        ClientConfig clientConfig = new DefaultClientConfig();
        //clientConfig.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING, Boolean.TRUE);
        this.client = Client.create(clientConfig);
        this.apiResource = this.client.resource(getConnector().getApiUrl());
    }

    /**
     * Executes the Hello request
     */
    private <T> T execute(WebResource webResource, String method, Class<T> returnClass) throws HelloException {
        ClientResponse clientResponse = webResource.accept(MediaType.TEXT_PLAIN_TYPE).method(method, ClientResponse.class);
        if (clientResponse.getStatus() == 200) {
            return clientResponse.getEntity(returnClass);
        } else {
            throw new HelloException(
                    String.format("ERROR - statusCode: %d - message: %s",
                            clientResponse.getStatus(), clientResponse.getEntity(String.class))
            );
        }
    }

    public String getHello(String company, String fname, String lname) throws HelloException {
        MultivaluedMap apiParams = new MultivaluedMapImpl();
        apiParams.add("company", company);
        apiParams.add("fname", fname);
        apiParams.add("lname", lname);
        WebResource webResource = getApiResource().path("hello").queryParams(apiParams);
        return execute(webResource, "GET", String.class);
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public WebResource getApiResource() {
        return apiResource;
    }

    public void setApiResource(WebResource apiResource) {
        this.apiResource = apiResource;
    }

    public HelloConnector getConnector() {
        return connector;
    }

    public void setConnector(HelloConnector connector) {
        this.connector = connector;
    }
}
