/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.hello.exception;

/**
 * Created by alexfernandezwhiteskylabs on 5/8/14.
 */
public class HelloException extends Exception {

    private static final long serialVersionUID = 1L;

    public HelloException() {
    }
    public HelloException(String message) {
        super(message);
    }

    public HelloException(Throwable cause) {
        super(cause);
    }

    public HelloException(String message, Throwable cause) {
        super(message, cause);
    }

}

